### ISSUE TITLE
CRFPP library not well supported on Windows

### ISSUE THREAD

**Issue by xanagit** [kermitt2/grobid#14] opened 2013-08-02 14:47 UTC
Lot of functions of CRFPP that works on Linux/Mac does not work at all on Windows.

On training (the function what is not recognized):
java.lang.UnsatisfiedLinkError: org.chasen.crfpp.CRFPPJNI.CRFPPTrainer_what(JLorg/chasen/crfpp/CRFPPTrainer;)Ljava/lang/String;
 at org.chasen.crfpp.CRFPPJNI.CRFPPTrainer_what(Native Method)
 at org.chasen.crfpp.CRFPPTrainer.what(CRFPPTrainer.java:41)
 at org.grobid.trainer.AbstractTrainer.train(AbstractTrainer.java:49)
 at org.grobid.trainer.AbstractTrainer.runTraining(AbstractTrainer.java:139)
 at org.grobid.trainer.NameHeaderTrainer.main(NameHeaderTrainer.java:93)

On server (the instanciation of Model is not supported: newModel):
java.lang.UnsatisfiedLinkError: org.chasen.crfpp.CRFPPJNI.new_Model(Ljava/lang/String;)J
        at org.chasen.crfpp.CRFPPJNI.new_Model(Native Method)
        at org.chasen.crfpp.Model.<init>(Model.java:46)
        at org.grobid.core.engines.ModelMap.getNewModel(ModelMap.java:101)
        at org.grobid.core.engines.ModelMap.getModel(ModelMap.java:87)
        at org.grobid.core.engines.ModelMap.initModels(ModelMap.java:64)
        at org.grobid.core.factory.AbstractEngineFactory.fullInit(AbstractEngineFactory.java:58)
        at org.grobid.service.GrobidRestService.<init>(GrobidRestService.java:74)
        ... 69 more

**Comment by kermitt2** [comment] 2015-08-20 11:12
Let's try to have Wapiti supported on Windows based on the fork https://github.com/boumenot/Wapiti

**Comment by lfoppiano** [comment] 2016-09-23 10:02
@Helfo we've integrated the ported version of Wapity for Windows 64bit (thanks to @boumenot). If you are still interested to try, you can just download the development version from master.
Would be great to have more intensive testing on different Windows versions running natively. 

I'm going to close this issue, since it's obsolete (CRFPP is not used anymore in GROBID). 
For any issue related to Windows and Wapiti, please write your comments on issue #74.

**Closed by lfoppiano** 2016-09-23 10:02 UTC
Labels: bug

**Comment by parvinB** [comment] 2017-04-12 05:27
maven :: 3.3.9
java :: jdk1.8.0_121
windows 7:: 32 bit

I am using grobid by batch mode please advise me for following error as soon a possible:: 
//Note : also describe how to integrate the Wapiti for Windows 32bit 

JarClassLoader: Warning: org/apache/lucene/analysis/cn/smart/hhmm/SegTokenFilter
.class in lib/lucene-analyzers-smartcn-4.5.1.jar is hidden by lib/wipo-analysers
-0.0.1.jar (with different bytecode)
JarClassLoader: Warning: org/w3c/dom/UserDataHandler.class in lib/xom-1.2.5.jar
is hidden by lib/xml-apis-1.4.01.jar (with different bytecode)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.grobid.core.utilities.Utilities.launchMethod(Utilities.java:396)
        at org.grobid.core.main.batch.GrobidMain.main(GrobidMain.java:171)
        ... 6 more
Caused by: java.lang.UnsatisfiedLinkError: fr.limsi.wapiti.WapitiJNI.loadModel(L
java/lang/String;)J
        at fr.limsi.wapiti.WapitiJNI.loadModel(Native Method)
        at fr.limsi.wapiti.Wapiti.loadModel(Wapiti.java:22)
        at org.grobid.core.jni.WapitiWrapper.getModel(WapitiWrapper.java:34)
        at org.grobid.core.jni.WapitiWrapper.getModel(WapitiWrapper.java:30)
        at org.grobid.core.jni.WapitiModel.init(WapitiModel.java:41)
        at org.grobid.core.jni.WapitiModel.<init>(WapitiModel.java:30)
        at org.grobid.core.engines.tagging.WapitiTagger.<init>(WapitiTagger.java
:19)
        at org.grobid.core.engines.tagging.TaggerFactory.getTagger(TaggerFactory

**Comment by parvinB** [comment] 2017-04-12 08:17
kermitt2 @lfoppiano 
maven :: 3.3.9
java :: jdk1.8.0_121
windows 7:: 32 bit

I am using grobid by batch mode please advise me for following error as soon a possible::
//Note : also describe how to integrate the Wapiti for Windows 32bit

JarClassLoader: Warning: org/apache/lucene/analysis/cn/smart/hhmm/SegTokenFilter
.class in lib/lucene-analyzers-smartcn-4.5.1.jar is hidden by lib/wipo-analysers
-0.0.1.jar (with different bytecode)
JarClassLoader: Warning: org/w3c/dom/UserDataHandler.class in lib/xom-1.2.5.jar
is hidden by lib/xml-apis-1.4.01.jar (with different bytecode)
Exception in thread "main" java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.simontuffs.onejar.Boot.run(Boot.java:340)
at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.grobid.core.utilities.Utilities.launchMethod(Utilities.java:396)
at org.grobid.core.main.batch.GrobidMain.main(GrobidMain.java:171)
... 6 more
Caused by: java.lang.UnsatisfiedLinkError: fr.limsi.wapiti.WapitiJNI.loadModel(L
java/lang/String;)J
at fr.limsi.wapiti.WapitiJNI.loadModel(Native Method)
at fr.limsi.wapiti.Wapiti.loadModel(Wapiti.java:22)
at org.grobid.core.jni.WapitiWrapper.getModel(WapitiWrapper.java:34)
at org.grobid.core.jni.WapitiWrapper.getModel(WapitiWrapper.java:30)
at org.grobid.core.jni.WapitiModel.init(WapitiModel.java:41)
at org.grobid.core.jni.WapitiModel.(WapitiModel.java:30)
at org.grobid.core.engines.tagging.WapitiTagger.(WapitiTagger.java
:19)
at org.grobid.core.engines.tagging.TaggerFactory.getTagger(TaggerFactory
