### ISSUE TITLE
the correspondence about tags or labels

### ISSUE THREAD

**Issue by Punchwes** [kermitt2/grobid#366] opened 2018-12-27 14:19 UTC
Hi,

I am quite confused about the tags in training files and resulting tei files in prediction phase.  Tags used for annotation seems not the same to the tagging label, they have a mapping relationship but I fail to find that. Such as in the tagginglabels file, there is` <section>, <paragraph>` tags but in result files only` <head>, <p> `can be found. I wonder where the transformation takes place? I've checked the saxparser and parser files, but I am still quite confused. 

Thanks in advance.

**Comment by kermitt2** [comment] 2018-12-29 04:46
Hello !

Training data are in TEI XML (flat TEI preserving stream order of the PDF), there is a mapping between TEI XML tag and labels used by the models in the SAX parsers corresponding to the model in `grobid-trainer`

Then the final results are serialized into a complex TEI XML (normalised order and more deeply structured). So there is also a mapping between the labels used by the models into this TEI, which is mainly done in the file TEIFormatter, and for substructures like date, person, etc. directly by the POJO classes under `org.grobid.core.data`.

Hope it makes thing clearer ! If not, don't hesitate to ask more.

**Comment by Punchwes** [comment] 2019-01-02 10:34
Hi,

I am a little bit confused about the head tag in fulltext model. In your fulltext training data, it seems that many of examples have their head tagged like this `<head level="1">2 The RTE System<lb/></head> `. 

The level attribute has been annotated, but the output of the `processFullText` seems not to produce information about the head level. I wonder how could I be possible to add the level information in the final output for the head level information is very important for my project ? It seems I can do it in the TEIFormatter.java file by changing something in `toTEITextPiece`.

Thanks in advance

**Comment by kermitt2** [comment] 2019-01-07 02:21
Hello @Punchwes !

The level information in the training data is not used. It was added at some point to make future evaluation and training possible. 

The header section level was outputted in the resulting TEI at some point in time but it was not reliable, and it could cause not well-formed resulting XML, so I removed it with the idea to work on that again in some future to make it reliable.

The approach I tested (and that I considered unreliable) was using additional labels subsection, subsubsection... for sub-levels. The problem is that with a CRF approach, we have super distant dependencies here that are not captured. 

I think the alternative approach (that could be more reliable and easier to control imho) would be to analyse the number informations of all the section header structure (extract this number, identify a numbering scheme, deduce some level options looking at the font information too, and validate that looking globally at all section numbering). That was the approach I was thinking so far to experiment next, but how concretely to implement it with a ML approach was not clear - I've not really thought about it. 

What do you think?

**Comment by Punchwes** [comment] 2019-01-09 09:50
Hi @kermitt2 ,

Thanks very much for your reply,

Yes, I think it is more reasonable and maybe accurate to develop a numbering scheme. I will firstly try to annotate on sub-sections and check the performance. If improvements are so hard to be obtained, I shall just replace all sub-sections to the upper-level one and try to figure out in the other direction.

Thanks so much again for your reply.

**Comment by kermitt2** [comment] 2019-01-23 14:01
Hi again @Punchwes ! I am closing this issue which was about xml tag/crf label correspondence.

I open a separate one about level and number of section header, to keep track of improvement on this aspect.

**Closed by kermitt2** 2019-01-23 14:01 UTC
