### ISSUE TITLE
Error with Building Grobid

### ISSUE THREAD

**Issue by jonsaadfalcon** [kermitt2/grobid#425] opened 2019-04-22 02:27 UTC
I have a Mac Pro and recently tried to build Grobid but received the following error after running the command ./gradlew run:

lawn-128-61-29-63:grobid jonsaadfalcon$ ./gradlew run

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.2'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by kermitt2** [comment] 2019-04-22 02:37
duplicate of #418 
Please see https://github.com/kermitt2/grobid/issues/418#issuecomment-480542345
If modifying `distributionUrl` in `grobid/gradle/wrapper/gradle-wrapper.properties` as indicated is not working with java version 11, you need to use a java version between 8 to 10.

**Closed by kermitt2** 2019-04-22 02:37 UTC
