### ISSUE TITLE
Affiliation extraction Error Ex2

### ISSUE THREAD

**Issue by adouib** [kermitt2/grobid#522] opened 2019-12-03 13:44 UTC
Dears all,

I have a pdf document with a specific format for authors and their affiliations (see attached document), where we have a groupe of authors in the first line and their affliation in the seconde line, after another groupe of authors in 3th line followed by their affiliation in the 4th line and so on.

We get two extraction errors :

1. The second group of authors is totaly ignored and not extracted as authors. 
2. For the rest of authors, we have one single affiliation in which the informations of the three affiliations are merged, specially the address information (see the extraction result below)
![CapTest2](https://user-images.githubusercontent.com/33157610/70056188-51a4d700-15db-11ea-8d6a-493eaf697baf.png)

```
<author>
	<persName xmlns="http://www.tei-c.org/ns/1.0"><forename type="first">R</forename><forename type="middle">C</forename><surname>Haight</surname></persName>
	<affiliation key="aff0">
		<orgName type="department" key="dep1">Los Alamos Neutron Science Center</orgName>
		<orgName type="department" key="dep2">DIF</orgName>
		<orgName type="department" key="dep3">Theoretical Division</orgName>
		<orgName type="laboratory">Los Alamos National Laboratory</orgName>
		<orgName type="institution">Los Alamos National Laboratory</orgName>
		**<address>
			<postCode>87545, F-91297, 87545</postCode>
			<settlement>Los Alamos, Arpajon, Los Alamos</settlement>
			<region>New Mexico, New Mexico</region>
			<country>USA, France, USA</country>
		</address>**
	</affiliation>
</author>
```

**Comment by kermitt2** [comment] 2019-12-04 18:38
Hello @adouib, thank you!

Could you add the PDF or give the DOI so that we can try to reproduce the error?
It could be a reading order problem, but impossible to say without the pdf.
Have you tried with the current master or latest stable version?

**Comment by kermitt2** [comment] 2020-08-11 11:12
Article is under paywall, I can't test it:
https://journals.aps.org/prc/abstract/10.1103/PhysRevC.83.034604

**Comment by lfoppiano** [comment] 2020-08-12 01:50
I've tested with this PDF, here the output: 

```xml
<sourceDesc>
                <biblStruct>
                    <analytic>
                        <author>
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">S</forename>
                                <surname>Noda</surname>
                            </persName>
                        </author>
                        <author role="corresp">
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">R</forename>
                                <forename type="middle">C</forename>
                                <surname>Haight</surname>
                            </persName>
                            <email>haight@lanl.gov</email>
                        </author>
                        <author>
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">R</forename>
                                <forename type="middle">O</forename>
                                <surname>Nelson</surname>
                            </persName>
                        </author>
                        <author>
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">M</forename>
                                <surname>Devlin</surname>
                            </persName>
                        </author>
                        <author>
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">J</forename>
                                <forename type="middle">M</forename>
                                <surname>O&amp;apos;donnell</surname>
                            </persName>
                        </author>
                        <author>
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">A</forename>
                                <surname>Chatillon</surname>
                            </persName>
                        </author>
                        <author>
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">T</forename>
                                <surname>Granier</surname>
                            </persName>
                        </author>
                        <author>
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">G</forename>
                                <surname>Bélier</surname>
                            </persName>
                        </author>
                        <author>
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">J</forename>
                                <surname>Taieb</surname>
                            </persName>
                        </author>
                        <author>
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">T</forename>
                                <surname>Kawano</surname>
                            </persName>
                        </author>
                        <author>
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">P</forename>
                                <surname>Talou</surname>
                            </persName>
                        </author>
                        <author>
                            <affiliation key="aff0">
                                <orgName type="department">Los Alamos Neutron Science Center</orgName>
                                <orgName type="institution">Los Alamos National Laboratory</orgName>
                                <address>
                                    <postCode>87545</postCode>
                                    <settlement>Los Alamos</settlement>
                                    <region>New Mexico</region>
                                    <country key="US">USA</country>
                                </address>
                            </affiliation>
                        </author>
                        <author>
                            <affiliation key="aff1">
                                <orgName type="institution">CEA</orgName>
                                <address>
                                    <addrLine>DAM, DIF</addrLine>
                                    <postCode>F-91297</postCode>
                                    <settlement>Arpajon</settlement>
                                    <country key="FR">France</country>
                                </address>
                            </affiliation>
                        </author>
                        <author>
                            <affiliation key="aff2">
                                <orgName type="department">Theoretical Division</orgName>
                                <orgName type="laboratory">Los Alamos National Laboratory</orgName>
                                <address>
                                    <postCode>87545</postCode>
                                    <settlement>Los Alamos</settlement>
                                    <region>New Mexico</region>
                                    <country key="US">USA</country>
                                </address>
                            </affiliation>
                        </author>
                        <author>
                            <affiliation key="aff3">
                                <orgName type="institution">Kyushu University</orgName>
                                <address>
                                    <addrLine>744 Motooka Nishi-ku</addrLine>
                                    <postCode>819-0395</postCode>
                                    <settlement>Fukuoka</settlement>
                                    <country key="JP">Japan</country>
                                </address>
                            </affiliation>
                        </author>
```


a) The first problem seems to be solved, the whole set of authors are extracted. 
b) The second problem is also not occurring and the affiliations are kept separately, 

however, it seems that they are not merged correctly with the authors. 

There is also the address for the corresponding author, Kyushu university is taken as affiliation.

**Comment by kermitt2** [comment] 2020-08-12 07:54
> There is also the address for the corresponding author, Kyushu university is taken as affiliation.

That part is correct - or at least as expected, for grobid this is an extra full affiliation (current affiliation of the first author). 

The attachment of affiliations need some more work in general for sure!

**Closed** 2022-10-31 06:54 UTC
Labels: error cases, implemented
