### ISSUE TITLE
Where to place model files for training

### ISSUE THREAD

**Issue by noob9721** [kermitt2/grobid#587] opened 2020-05-25 20:37 UTC
After the data model generated from many PDFs using createTraining command and stored in a file, **which location** should it be placed in for further training models to check for accuracy and precision?
Please specify the location for a successful build.

**Comment by kermitt2** [comment] 2020-05-26 10:36
Hi @noob9721 

This is documented here -> https://grobid.readthedocs.io/en/latest/Training-the-models-of-Grobid/#train-and-evaluate

and some more information here -> https://grobid.readthedocs.io/en/latest/training/General-principles/

**Comment by noob9721** [comment] 2020-05-26 22:53
after replacing files at grobid/grobid-trainer/resources/dataset/*MODEL*/corpus/  with my generated training data, BUILD FAILED. how to make it successful

![Untitled](https://user-images.githubusercontent.com/65922353/82957910-b876dc00-9fd1-11ea-9d82-1e4924bec7ca.png)

**Comment by kermitt2** [comment] 2020-05-27 02:14
Grobid can't assemble the training data so either the files are not found or their format is not recognized. Could you give the full build trace (there are likely error message above the part you made a screenshot) and give more details on your copy your training files?

**Comment by noob9721** [comment] 2020-05-27 15:51
19 files of different models were generated per PDF (working with 100 PDFs for now) after running createTraining-
072131093.training.figure
072131093.training.figure.tei.xml
072131093.training.fulltext
072131093.training.fulltext.tei.xml
072131093.training.header
072131093.training.header.affiliation.tei.xml
072131093.training.header.authors.tei.xml
072131093.training.header.reference.xml
072131093.training.header.tei.xml
072131093.training.references.authors.tei.xml
072131093.training.references.referenceSegmenter
072131093.training.references.referenceSegmenter.rawtxt
072131093.training.references.referenceSegmenter.tei.xml
072131093.training.references.tei.xml
072131093.training.segmentation
072131093.training.segmentation.rawtxt
072131093.training.segmentation.tei.xml
072131093.training.table
072131093.training.table.tei.xml
 
I separated files of different models and replaced them at their respective positions in grobid/grobid-trainer/resources/dataset/*MODEL*/corpus/. 

This is a screenshot for header training,
in grobid-trainer/resources/dataset/header/corpus/tei  where I deleted inbuilt *.tei.xml files and replaced with my generated *.tei.xml file (the rest .tei files were left untouched)
and in grobid-trainer/resources/dataset/header/corpus/header  I deleted all inbuilt *.header files and replaced with my generated *.header files

then tried running  ./gradlew train_header  after coming to grobid main directory

![github](https://user-images.githubusercontent.com/65922353/83042612-78f6d100-a05f-11ea-9375-2f56632172fe.png)

**Comment by kermitt2** [comment] 2020-05-28 12:12
* you could remove the `*.tei` files under `resources/dataset/header/corpus/tei/` too, because they won't be used if the corresponding `*.header` have been deleted under `resources/dataset/header/corpus/headers/` - they will be ignored anyway but it's cleaner

* could you share at least one of your generated new training file (both the `*.tei.xml` and the corresponding `*.header`) so that I can try to reproduce the error

**Comment by noob9721** [comment] 2020-05-30 03:02
I have tried removing the *.tei files from mentioned location too but it gave the same error. So I assumed that they're not the problem here

These are from all 100 PDFs 

[grobid.zip](https://github.com/kermitt2/grobid/files/4705016/grobid.zip)

**Comment by kermitt2** [comment] 2020-06-13 13:59
I've tried your files and indeed the `.header` files are not loaded, there's something incorrect in the way the files are found (I've not looked at this part since 4 years I think...). Sorry for that! 

As I have worked on a completely revised version of the header model (PR #580), which is giving better results with far less training data and which is more tested, robust and active (the new model is also more adapted to complex header and pre-prints), here what's to do to have an updated header model: 

- user the branch `update_header`: `git checkout update_header`

- [regenerate the training files from your PDF](https://grobid.readthedocs.io/en/latest/Grobid-batch/#createtraining) as you did, the files will be different with new labels, new features

- move the training files as before, `*.tei.xml` to `resources/dataset/header/corpus/tei/` and `*.header` to `resources/dataset/header/corpus/raw/` (warning, the name of the last directory has changed to be consistent with the other models)

- launch the training as before: `./gradlew train_header`

This should work and it's much better to use to use this new version of the header model - it will be merged with the master in a close future.

**Closed** 2022-10-31 06:54 UTC
Labels: implemented
