### ISSUE TITLE
after edit training xml can we run perticular file to update in output

### ISSUE THREAD

**Issue by dineshbs7** [kermitt2/grobid#386] opened 2019-02-11 06:52 UTC

**Comment by dineshbs7** [comment] 2019-02-11 06:56
Dear Sir,
i have data(training data) for updating month tag in bibliography section .where i need to add i.e in date module/reference module but here training data is created for only some module

**Comment by kermitt2** [comment] 2019-02-13 21:41
duplicate of #384

**Closed by kermitt2** 2019-02-13 21:41 UTC
