### ISSUE TITLE
Date is taken under 'note'

### ISSUE THREAD

**Issue by naimavahab** [kermitt2/grobid#248] opened 2017-10-18 06:49 UTC
Date is nested under 'note' 
`<note type="submission">
Received: 23 March 2017
<lb/>
Accepted: 10 May 2017
<lb/>
</note>
<date>
Published: xx xx xxxx
<lb/>
</date>`

And published date is coming as xxxx

**Comment by kermitt2** [comment] 2017-10-18 07:44
Hello @naimavahab 

This is the expected behavior, only the publication date (by far the most useful in general usages) is annotated as `<date>`. The other dates like editorial/history dates are under notes because we want to distinguish the publication date from the others. 
If the publication date is not specified (with xxxx typically in the preprint as in your example), the xxxx is tagged as date. 

We could change this behavior, but it implies extending the model and the training data to a larger variety of date types.

**Comment by naimavahab** [comment] 2017-10-18 07:50
![pdf-error](https://user-images.githubusercontent.com/13636783/31706519-bf77d546-b3d8-11e7-9ced-5240c59a849d.png)
Publication date only coming under notes.. 
Can you give  an idea of how to extend the model.. do we have to train wapiti/crf..?

**Comment by naimavahab** [comment] 2017-10-18 07:51
[Lonjon-2017-HpaB-Dependent Secretion of Type I.pdf](https://github.com/kermitt2/grobid/files/1393796/Lonjon-2017-HpaB-Dependent.Secretion.of.Type.I.pdf)
PFA..Pdf for reference...

**Comment by kermitt2** [comment] 2017-10-18 08:20
In your example, the publication date is obfuscated as a bitmap, you can't extract it, what's available is `Received: 23 March 2017 Accepted: 10 May 2017 Published: xx xx xxxx` (this is visible by doing a cut and paste). 

From that the TEI is giving the best we could expect -> `<date type="published">Published: xx xx xxxx</date>` 

By selecting the "consolidation" option, GROBID will get the actual publication date from CrossRef web API:
`<date type="published" when="2017-12">Published: xx xx xxxx</date>`
(distinguished as an attribute @when)

So this illustrates how hard it is to process publications from mainstream publishers. Here the final publication date is probably not obfuscated on purpose to hide anything, it is, I suppose, just "stamped" as a bitmap at a particular position of an already produced PDF, a bit a dirty hack but it's not their goal to produce reusable PDF. 

As for extending the model to extract various types of editorial dates, the main issue is that doing it in the header model supposes to review the 2500 annotated training headers for these extra annotations. 

A KISS approach I think would be to use a NER (like grobid-ner :D ) to extract the dates from the notes.

**Comment by kermitt2** [comment] 2017-11-26 05:51
I am closing this issue, as the problem comes from obfuscated text in the PDF and there's nothing GROBID can reasonably do on it.

**Closed by kermitt2** 2017-11-26 05:51 UTC
