### ISSUE TITLE
zombie pdftoxml processes when running in docker

### ISSUE THREAD

**Issue by benhyland** [kermitt2/grobid#312] opened 2018-04-25 13:24 UTC
The Grobid Docker image seems to suffer from zombie pdftoxml processes.

Here is the process table of a Grobid container under some load:
```
# ps xo pid,ppid,comm
   PID   PPID COMMAND
     1      0 java
   185      0 sh
   700      1 pdftoxml_server <defunct>
   701      1 pdftoxml_server <defunct>
   702      1 pdftoxml_server <defunct>
   703      1 pdftoxml_server <defunct>
   706      1 pdftoxml_server <defunct>
<snip>
  3559      1 pdftoxml_server <defunct>
  3562      1 pdftoxml_server
  3563   3562 sleep
  3565      1 pdftoxml_server
  3566   3565 sleep
  3567      1 pdftoxml
  3568   3567 pdftoxml_server
  3569   3568 sleep
  3570   2453 ps
```

Eventually, the process table of the host fills up, which means all apps on the same host are unable to create new OS threads or spawn new processes.

It seems like https://github.com/Yelp/dumb-init or https://github.com/krallin/tini might be the best solutions.
There is a good explanation and a few other blogs and alternatives linked in the dumb-init readme.

In the meantime, we are using an image along the lines of

```
FROM lfoppiano/grobid:0.5.1

ARG DUMB_INIT_VERSION=1.2.1
ADD https://github.com/Yelp/dumb-init/releases/download/v${DUMB_INIT_VERSION}/dumb-init_${DUMB_INIT_VERSION}_amd64 /usr/bin/dumb-init
RUN chmod +x /usr/bin/dumb-init

WORKDIR /opt/grobid
ENTRYPOINT ["/usr/bin/dumb-init"]
CMD ["./grobid-service/bin/grobid-service", "server", "grobid-service/config/config.yaml"]
```

We can't just use Docker's `--init` flag (https://docs.docker.com/engine/reference/run/#specify-an-init-process) to get tini, since we run on Kubernetes and I don't think that behaviour is exposed.

**Comment by Aazhar** [comment] 2018-04-27 09:42
Hello,
Have you tried with bash or supervisord as an init system ?
Otherwise the java process is supposed to manage its childs correctly, could you provide the logs output ?

**Comment by benhyland** [comment] 2018-04-27 10:49
@Aazhar Hi there,

I haven't tried bash or supervisord as I was originally using the stock grobid image.

By 'managing its childs correctly' do you mean that any JVM should call waitpid on adopted orphan processes automatically? This doesn't seem to be happening.

**Comment by lfoppiano** [comment] 2018-05-29 11:41
@benhyland I'm trying to reproduce your problem, and with the current version 0.5.1 I cannot really verify it since the image doesn't ship any additional commands. How can I get in the status you are showing in your first comment?

**Comment by benhyland** [comment] 2018-05-29 12:17
Hi @lfoppiano , thanks for looking into this.

The command above is just `ps` with custom output to reduce noise: `ps xo pid,ppid,comm`.
I just wanted to show evidence of zombie processes.
I may have had to manually add `ps` to the image, sorry for any confusion.
You could do that with `apt update && apt install procps`.

**Comment by lfoppiano** [comment] 2018-05-29 15:10
@benhyland Thanks! I tried `apt-get install` forgetting to run `update` :-D indeed the issue is problematic. I have never had though we would have this kind of issue. I'm wondering why is this happening only with docker (linux and mac are working fine)

**Comment by lfoppiano** [comment] 2018-05-29 16:30
ok. I see whether integrating tini in our dockerfile would work without the `--init` command and then maybe you could test it directly and let me know if this work without any additional workaround?

**Comment by benhyland** [comment] 2018-05-29 16:31
I can check any updated image you produce without much difficulty.
Thanks very much!

**Comment by benhyland** [comment] 2018-05-29 20:09
:+1: 0.6.0-SNAPSHOT seems to fix this issue.

**Comment by lfoppiano** [comment] 2018-05-29 20:32
OK, I'll try to fix the 0.5.1 version so we have the latest stable docker image working properly

**Comment by lfoppiano** [comment] 2018-05-29 23:21
@benhyland I've updated and tested the image 0.5.1 and should work fine, please give it a try to confirm the fix is retrofit on the the latest stable version ;-)

**Comment by benhyland** [comment] 2018-05-30 09:46
@lfoppiano `0.5.1` looks good as well now. tyvm

**Comment by lfoppiano** [comment] 2018-05-30 09:56
Great! I can close this issue then. Thanks a lot for your patience and for helping me with the tests.

**Closed by lfoppiano** 2018-05-30 09:56 UTC
