### ISSUE TITLE
Wapiti on windows 64bit, UnsatisfiedLinkError when running grobid on windows

### ISSUE THREAD

**Issue by KevinVdV** [kermitt2/grobid#74] opened 2015-09-04 12:08 UTC
We are trying to use grobid on a windows installation but getting the following error:

`java.lang.UnsatisfiedLinkError: fr.limsi.wapiti.WapitiJNI.loadModel(Ljava/lang/String;)J
at fr.limsi.wapiti.WapitiJNI.loadModel(Native Method)
	at fr.limsi.wapiti.Wapiti.loadModel(Wapiti.java:22)
	at org.grobid.core.jni.WapitiWrapper.getModel(WapitiWrapper.java:34)
	at org.grobid.core.jni.WapitiWrapper.getModel(WapitiWrapper.java:30)
	at org.grobid.core.jni.WapitiModel.init(WapitiModel.java:40)
	at org.grobid.core.jni.WapitiModel.<init>(WapitiModel.java:29)
	at org.grobid.core.engines.tagging.WapitiTagger.<init>(WapitiTagger.java:18)
	at org.grobid.core.engines.tagging.TaggerFactory.getTagger(TaggerFactory.java:24)
	at org.grobid.core.engines.AbstractParser.<init>(AbstractParser.java:28)
	at org.grobid.core.engines.AbstractParser.<init>(AbstractParser.java:23)
	at org.grobid.core.engines.HeaderParser.<init>(HeaderParser.java:53)
	at org.grobid.core.engines.EngineParsers.getHeaderParser(EngineParsers.java:56)
	at org.grobid.core.engines.Engine.processHeader(Engine.java:427)
	at org.grobid.core.engines.Engine.processHeader(Engine.java:402)`

The code used to retrieve our teiString:

`GrobidProperties.set_GROBID_HOME_PATH(pGrobidHome);
GrobidProperties.setGrobidPropertiesPath(pGrobidProperties);
MockContext.setInitialContext(pGrobidHome, pGrobidProperties);
GrobidProperties.getInstance();
Engine engine = GrobidFactory.getInstance().createEngine();
// Biblio object for the result
BiblioItem resHeader = new BiblioItem();
teiString = engine.processHeader(f.getAbsolutePath(), false, resHeader);`

The code above works perfectly on the latest Mac OSX but we cannot get to run on Windows Server 2008.
We are using a 64 bit "jdk1.7.0_71" on the windows system.

**Comment by kermitt2** [comment] 2015-09-04 12:30
Hello Kevin,

As mentionned on the readme file and in the documentation, Windows is currently not supported by Grobid. There is no Wapiti library with JNI for Windows included in Grobid - only for Linux and Mac OS. 

You might be able to use Grobid on Windows with CRP++ (instead Wapiti) as CRF native library but only on 32 bits environment, but I am not able to test it - so no guarantee! 

The good news is that there is a port of Wapiti for Windows available here: https://github.com/boumenot/Wapiti
So we should be able to support Windows in a close future. If you are able to compile this version and provide the dll, I can add it to Grobid.

**Comment by lfoppiano** [comment] 2016-09-23 09:56
Hi @KevinVdV, 
    today we've integrated the ported version of Wapity for Windows 64bit, thanks to the great job of @boumenot. 

If you are still interested to try, you can just download the development version from master. 
Would be great to have more intensive testing on different Windows versions running natively. 

Cheers
Luca

**Comment by lfoppiano** [comment] 2016-10-04 08:29
I close this issue, should you find any problems, feel free to reopen it ;)

**Closed by lfoppiano** 2016-10-04 08:29 UTC
Labels: enhancement

**Comment by parvinB** [comment] 2017-04-12 09:16
@lfoppiano 
maven :: 3.3.9
java :: jdk1.8.0_121
windows 7:: 32 bit

I am using grobid by batch mode please advise me for following error as soon a possible::
//Note : also describe how to integrate the Wapiti for Windows 32bit

JarClassLoader: Warning: org/apache/lucene/analysis/cn/smart/hhmm/SegTokenFilter
.class in lib/lucene-analyzers-smartcn-4.5.1.jar is hidden by lib/wipo-analysers
-0.0.1.jar (with different bytecode)
JarClassLoader: Warning: org/w3c/dom/UserDataHandler.class in lib/xom-1.2.5.jar
is hidden by lib/xml-apis-1.4.01.jar (with different bytecode)
Exception in thread "main" java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.simontuffs.onejar.Boot.run(Boot.java:340)
at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.grobid.core.utilities.Utilities.launchMethod(Utilities.java:396)
at org.grobid.core.main.batch.GrobidMain.main(GrobidMain.java:171)
... 6 more
Caused by: java.lang.UnsatisfiedLinkError: fr.limsi.wapiti.WapitiJNI.loadModel(L
java/lang/String;)J
at fr.limsi.wapiti.WapitiJNI.loadModel(Native Method)
at fr.limsi.wapiti.Wapiti.loadModel(Wapiti.java:22)
at org.grobid.core.jni.WapitiWrapper.getModel(WapitiWrapper.java:34)
at org.grobid.core.jni.WapitiWrapper.getModel(WapitiWrapper.java:30)
at org.grobid.core.jni.WapitiModel.init(WapitiModel.java:41)
at org.grobid.core.jni.WapitiModel.(WapitiModel.java:30)
at org.grobid.core.engines.tagging.WapitiTagger.(WapitiTagger.java
:19)
at org.grobid.core.engines.tagging.TaggerFactory.getTagger(TaggerFactory

**Comment by lfoppiano** [comment] 2017-04-25 14:41
@parvinB The reason of your exception is because wapiti is supported only on windows 64bit. 

You either move to windows 64bit or you try to compile wapiti on windows 32bit: I don't remember but should be either https://github.com/boumenot/Wapiti or https://github.com/kermitt2/Wapiti  (good luck with that)

**Comment by parvinB** [comment] 2017-04-27 05:19
@lfoppiano 
thanks

**Comment by kripash12** [comment] 2018-12-03 17:12
I have a Windows 64 bit but still get the same error, any ideas why?

Causing: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.UnsatisfiedLinkError: fr.limsi.wapiti.WapitiJNI.loadModel(Ljava/lang/String;)J
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
! at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
! at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:674)
! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at org.eclipse.jetty.server.Server.handle(Server.java:531)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
! at java.lang.Thread.run(Thread.java:748)
