### ISSUE TITLE
PDF2XML crash

### ISSUE THREAD

**Issue by dwatsonbynes** [kermitt2/grobid#161] opened 2017-02-21 12:39 UTC
Hi,

I am using Grobid on a Windows 64 bit machine. When PDF2XML fails on certain files, the process crashes and generates an error window for each time it crashes. Is there any solution to prevent the window from appearing or PDF2XML failing for those files?

**Comment by kermitt2** [comment] 2017-04-06 19:38
Hello !

Could you provide one or two examples of these files for reproducing the error? (per email to me if it not public)

As info, I've worked on a new fork of pdf2xml which should prevent most of the crash that I've observed so far, but probably not all of them. It will be used in a future release because it requires some changes in GROBID and in training data.

**Comment by kermitt2** [comment] 2017-05-11 17:04
see #185  and #166  
need to recompile pdf3xml fork for Windows 64

**Comment by lfoppiano** [comment] 2017-08-04 14:27
Should be fixed with commit 75536cd. See [comment](https://github.com/kermitt2/grobid/issues/185#issuecomment-320262206) on issue #185

**Closed by lfoppiano** 2017-08-04 14:27 UTC
Labels: need help
