### ISSUE TITLE
Problem proccessing PDF: [PDFALTO_CONVERSION_FAILURE]

### ISSUE THREAD

**Issue by cerulij** [kermitt2/grobid#894] opened 2022-02-25 00:13 UTC
Hey everyone, I've been having this issue when I try to process a PDF using the Java API. I'm using macOS monterey:

**org.grobid.core.exceptions.GrobidException: [PDFALTO_CONVERSION_FAILURE] PDF to XML conversion failed on pdf file /xxx/Wang_paperAVE2008.pdf** 
	at org.grobid.core.document.DocumentSource.processPdfaltoThreadMode(DocumentSource.java:209)
	at org.grobid.core.document.DocumentSource.pdfalto(DocumentSource.java:155)
	at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:64)
	at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:50)
	at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:42)
	at org.grobid.core.engines.CitationParser.processingReferenceSection(CitationParser.java:396)
	at org.grobid.core.engines.Engine.processReferences(Engine.java:237)

I'm also trying on the pdf in the grobid-example repo (Wang_paperAVE2008.pdf). The code is pretty much the basic usage:

(...)

      Engine engine = GrobidFactory.getInstance().createEngine();

      BiblioItem result = new BiblioItem();

      String tei = engine.processHeader(pdfPath, 0, result);

Do you know what I should do?

Thank you!

**Comment by NorbertSandor** [comment] 2022-04-19 18:52
I get the same exception on Win10.

**Comment by kermitt2** [comment] 2022-04-19 18:58
Hello !

@NorbertSandor Windows is not supported anymore by Grobid, the binaries for pdfalto are missing. 

@cerulij it's likely that the binaries for pdfalto shipped with Grobid are not compatible with the recent macOS monterey

@lfoppiano what do you think about the macOS monterey issue?

**Comment by lfoppiano** [comment] 2022-04-20 08:33
I tested grobid with MacOs Monterey and it works fine. 

@cerulij could you share the whole example or the project so that I could have a look? At first glance might be that the grobid home is not found perhaps?

**Comment by kermitt2** [comment] 2022-04-20 11:10
@NorbertSandor just pointing to the documentation about the non-support of Windows https://grobid.readthedocs.io/en/latest/Troubleshooting/#windows-related-issues
Using docker is a convenient way to have a Grobid service working on windows, see https://grobid.readthedocs.io/en/latest/Grobid-docker/

**Comment by karatekaneen** [comment] 2022-04-25 12:10
Ran into similar issue when generating training data on Monterey even on files that has been working in the past. It did work when I built and ran within the CRF Docker image so think this is MacOS specific

Versions:
Grobid: [0.7.2-SNAPSHOT](https://github.com/kermitt2/grobid/commit/184a94eaab83019f321e908da5044ceacbc82240)
MacOS: 12.3.1 (21E258)
Java: java version "1.8.0_40-ea" Java(TM) SE Runtime Environment (build 1.8.0_40-ea-b23)


```
/Users/NAME/grobid-training/new/Asano_et_al-2020-Cochrane_Database_of_Systematic_Reviews.pdf
apr 25, 2022 1:53:37 EM org.grobid.core.engines.Engine batchCreateTraining
ALLVARLIG: An error occured while processing the following pdf: /Users/NAME/grobid-training/new/Asano_et_al-2020-Cochrane_Database_of_Systematic_Reviews.pdf
org.grobid.core.exceptions.GrobidException: [GENERAL] An exception occurred while running Grobid training data generation for full text.
	at org.grobid.core.engines.FullTextParser.createTraining(FullTextParser.java:1452)
	at org.grobid.core.engines.Engine.createTraining(Engine.java:462)
	at org.grobid.core.engines.Engine.batchCreateTraining(Engine.java:566)
	at org.grobid.core.engines.ProcessEngine.createTraining(ProcessEngine.java:379)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.grobid.core.utilities.Utilities.launchMethod(Utilities.java:339)
	at org.grobid.core.main.batch.GrobidMain.main(GrobidMain.java:189)
Caused by: org.grobid.core.exceptions.GrobidException: [PDFALTO_CONVERSION_FAILURE] PDF to XML conversion failed on pdf file /Users/NAME/grobid-training/new/Asano_et_al-2020-Cochrane_Database_of_Systematic_Reviews.pdf
	at org.grobid.core.document.DocumentSource.processPdfaltoThreadMode(DocumentSource.java:209)
	at org.grobid.core.document.DocumentSource.pdfalto(DocumentSource.java:155)
	at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:64)
	at org.grobid.core.engines.FullTextParser.createTraining(FullTextParser.java:1001)
	... 9 more
```

**Comment by lfoppiano** [comment] 2022-04-26 20:56
@karatekaneen I will have a look

**Comment by lfoppiano** [comment] 2022-04-28 03:09
It seems that the grobid server works fine. In such case pdfalto is ran in "standalone server mode" and it works. When you run the process to generate the training data, pdfalto runs in "threaded mode" and, for some obscure reason, the pdfalto process fails. 
I blame macOs :-) 

Even I tested pdfalto from the command line and it works...

As a last resort I figured out that the problem is the ulimit stuff ran before pdfalto: 

```
(base) Lucas-MacBook-Pro:libs lfoppiano$ ulimit -Sv 6242304 && /Users/lfoppiano/development/projects/grobid/grobid-home/pdfalto/mac-64/pdfalto -fullFontName -noLineNumbers -noImage  -annotation  -outline  -filesLimit 2000  '/Users/lfoppiano/Downloads/grobid/in/dys041.pdf' /Users/lfoppiano/Downloads/grobid/out/bao.xml 
bash: ulimit: virtual memory: cannot modify limit: Invalid argument
```

**Comment by lfoppiano** [comment] 2022-06-20 03:53
Furthermore, it's possible to fix this by adding 
```java
                if (!SystemUtils.IS_OS_WINDOWS && !SystemUtils.IS_OS_MAC) {
``` 

in line 149 of `DocumentSource.java`. However the ulimit will not changed and the memory limit configuration will not be applied for `mac Os`. 

The second option is to run the training data generation in server mode. 

@kermitt2 I can push accordingly with your preference.

**Comment by lfoppiano** [comment] 2022-07-24 22:57
I think this was with PR #926. @cerulij , @karatekaneen  could you please check it out and if everything works, close this issue? 👍

**Closed** 2022-10-24 01:13 UTC
Labels: macOS-specific, implemented
