### ISSUE TITLE
Java Issue on Grobid

### ISSUE THREAD

**Issue by jonsaadfalcon** [kermitt2/grobid#418] opened 2019-04-06 19:50 UTC
Hello, I'm trying to run grobid on MacOS but I encountered an issue when trying to build on gradle. I received the following exception:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.2'.

I updated the gradle version but still received the same error. Any advice is greatly appreciated.

**Comment by kermitt2** [comment] 2019-04-06 19:58
Hello @jonsaadfalcon !
Did you try this gradle version -> https://grobid.readthedocs.io/en/latest/Troubleshooting/#wrong-java-version

**Comment by jonsaadfalcon** [comment] 2019-04-06 20:35
I did that but I still get the same Java version error.

**Comment by jonsaadfalcon** [comment] 2019-04-06 20:46
> Hello @jonsaadfalcon !
> Did you try this gradle version -> https://grobid.readthedocs.io/en/latest/Troubleshooting/#wrong-java-version

I did that but I still get the same Java version error.

**Comment by kermitt2** [comment] 2019-04-06 22:20
Ok I think JDK 11 is really very recent (released last September), never tested it. Java 11 is only supported by gradle 5 since last November, so maybe you could try this:
http://services.gradle.org/distributions/gradle-5.3-rc-3-bin.zip

... though that might not be supported by the gradle wrapper...  

Otherwise, it is better to use a jdk version "officially" supported by grobid (jdk 1.8 or 10).

**Comment by Aazhar** [comment] 2019-04-11 16:18
I've got same issue trying to install grobid on ubuntu 18 that comes with java 10 by default.

**Comment by kermitt2** [comment] 2019-04-11 16:20
For java 10, normally this works 
https://grobid.readthedocs.io/en/latest/Troubleshooting/#wrong-java-version
no?

**Comment by Aazhar** [comment] 2019-04-12 10:36
So compiling grobid on ubuntu 18 with the default java version :
> openjdk version "10.0.2"

I'm getting an error from jacoco :

`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:510)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:522)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
        at org.jacoco.agent.rt.internal_932a715.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:139)
        at org.jacoco.agent.rt.internal_932a715.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:100)
        at org.jacoco.agent.rt.internal_932a715.PreMain.createRuntime(PreMain.java:55)
        at org.jacoco.agent.rt.internal_932a715.PreMain.premain(PreMain.java:47)
        ... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
        at java.base/java.lang.Class.getField(Class.java:1958)
        at org.jacoco.agent.rt.internal_932a715.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:137)
        ... 9 more
FATAL ERROR in native method: processing of -javaagent failed`

So the grobid-core tests are passing after updating jacoco to toolVersion='0.8.2'

Then this error appears regarding jetty apparently:

`WARNING: HK2 service reification failed for [org.glassfish.jersey.message.internal.DataSourceProvider] with an exception:
    MultiException stack 1 of 2
    java.lang.NoClassDefFoundError: javax/activation/DataSource
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3090)
        at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2316)
        at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1308)
        at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1304)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.jvnet.hk2.internal.Utilities.getAllConstructors(Utilities.java:1304)
        at org.jvnet.hk2.internal.Utilities.findProducerConstructor(Utilities.java:1247)
        at org.jvnet.hk2.internal.DefaultClassAnalyzer.getConstructor(DefaultClassAnalyzer.java:83)
        at 
`

the workaround for this would be to add a dependency (corresponding to the missing package):

> compile "javax.activation:activation:1.1.1"

Then another error related to powermock is showing and after updating to latest beta version everything goes fine (without changing gradle version)

**Comment by kermitt2** [comment] 2019-04-12 12:01
In principle you should not have these issues with OpenJDK 10.0.2 
see https://github.com/kermitt2/grobid/issues/342

**Comment by kermitt2** [comment] 2019-04-12 12:03
or are you testing with `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10-all.zip` ?

**Comment by kermitt2** [comment] 2019-04-15 09:08
I've just pushed da0a8f1d44b01f61b90ac4aa144bb4c520fecefb an update of the dependencies and gradle version to support JVM 10 (and lower!) without requiring any additional modifications.   
Is it working for you @Aazhar  ?

**Comment by Aazhar** [comment] 2019-04-16 08:09
@kermitt2 yes everything good now, thanks

**Comment by kermitt2** [comment] 2019-06-27 15:55
Do we still have issues with java version 11 ?

**Comment by jonsaadfalcon** [comment] 2019-06-27 17:22
No not anymore

**Comment by kermitt2** [comment] 2019-06-27 17:33
thanks a lot @jonsaadfalcon ! let's close the issue.

**Closed by kermitt2** 2019-06-27 17:33 UTC
