### ISSUE TITLE
Not identifying month tag

### ISSUE THREAD

**Issue by dineshbs7** [kermitt2/grobid#393] opened 2019-02-13 10:29 UTC

**Comment by dineshbs7** [comment] 2019-02-13 10:34
dear sir,
issue 1: Not identifying month tag(Mar.1998)
input ref is : 
A. Barak and O. La’adan. The MOSIX multicomputer operating system for high performance luster computing. Future Generation Computer Systems,13(4–5):361–372, Mar. 1998.

output ref is: 
<monogr>
		<title level="j">Future Generation Computer Systems</title>
		<imprint>
			<biblScope unit="volume">13</biblScope>
			<biblScope unit="issue">4-5</biblScope>
			<biblScope unit="page" from="361" to="372" />
			<date type="published" when="1998-03" />
		</imprint>
	</monogr>

**Comment by dineshbs7** [comment] 2019-02-13 10:35
<monogr>
		<title level="j">Future Generation Computer Systems</title>
		<imprint>
			<biblScope unit="volume">13</biblScope>
			<biblScope unit="issue">4-5</biblScope>
			<biblScope unit="page" from="361" to="372" />
			<date type="published" when="1998-03" />
		</imprint>
	</monogr>

**Comment by kermitt2** [comment] 2019-02-13 21:38
duplicate of #394 
Please @dineshbs7 don't open several times an issue for the same problem, this is counter-productive for you and uncool in an open source project.

**Closed by kermitt2** 2019-02-13 21:38 UTC
